### ISSUE TITLE
zmq pub/sub模式下，多个pub绑定同一个地址，只有一个pub能绑定成功

### ISSUE THREAD

**Issue by DuckDuckDuck0** [DuckDuckDuck0/ft#15]
问题描述：
策略向ft_trader发消息是通过zmq pub/sub模式。
ft_trader为sub，策略为pub，所以同一时间无法有多个策略绑定到同一个ft_trader

解决方案(TODO)：
方案一：采用zmq xpub/xsub模式
方案二：使用redis来发送交易指令
方案三：使用共享内存队列发送交易指令

**Comment by zfsamzfsam** [comment]
几种方案,并不矛盾,可以都提供,这样**扩展性**更强!!!
    甚至可以和其他平台(eg: vnpy等python平台)对接

**Comment by DuckDuckDuck0** [comment]
@zfsamzfsam 好提议，现在的pubsub模块接口再完善一下就可以提供更灵活的扩展了

**Comment by zfsamzfsam** [comment]
方案三：使用共享内存队列发送交易指令

可参考:

yijinjing-lite----c++, low-latency in-porcess communication via mmap
	https://github.com/7starsea/yijinjing-lite
	c++, low-latency in-porcess communication via mmap
	yijinjing-lite is a standalone version of yijinjing in kungfu. We truly focus on low-latency in-process communication.

**Comment by DuckDuckDuck0** [comment]
嗯嗯，基本思想就是每个策略一个ring buffer
