### ISSUE TITLE
tick延时有点大，spdlog显示从ctp到策略达500us

### ISSUE THREAD

**Issue by songzhao831** [DuckDuckDuck0/ft#19]
在ctp附近加的log，和策略ontick加的log比较。

2021-03-25 02:04:39.057.057464 [error][] : instrumentid=ag2106
2021-03-25 02:04:39.057.057794 [info][] : GridStrategy::on_tick ft::datetime::Datetime(2021, 3, 25, 2, 4, 38, 500000),id:au2106, last_price:367.36, grid:5239.00, long:0, short:0, trades:1

有什么办法能减少这个延迟么， 比如跳过redis直接先送到策略。

**Comment by DuckDuckDuck0** [comment]
spdlog本身耗时就很大，会有一两百微秒的时延，所以用spdlog测量的时间误差比较大
先保证时间能够准确测量，在tick中加入当前毫秒时间字段
struct TickData : public pubsub::Serializable<TickData> {
  uint64_t current_time_us;   // 加入该字段
  MarketDataSource source;
  datetime::Datetime datetime;

  uint32_t ticker_id;
  double last_price = 0;
  double open_price = 0;
  double highest_price = 0;
  double lowest_price = 0;
  double pre_close_price = 0;
  double upper_limit_price = 0;
  double lower_limit_price = 0;
  uint64_t volume = 0;
  uint64_t turnover = 0;
  uint64_t open_interest = 0;

  double ask[kMaxMarketLevel]{0};
  double bid[kMaxMarketLevel]{0};
  int ask_volume[kMaxMarketLevel]{0};
  int bid_volume[kMaxMarketLevel]{0};

  struct {
    double iopv;
  } etf;

  SERIALIZABLE_FIELDS(current_time_us, source, datetime, ticker_id, last_price, open_price, highest_price,
                      lowest_price, pre_close_price, upper_limit_price, lower_limit_price, volume,
                      turnover, open_interest, ask, bid, ask_volume, bid_volume, etf.iopv);
};

在收到行情时，先在tick中记录当前时间
uint64_t GetCurrentTimeUs() {
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_nsec / 1000 + ts.tv_sec * 1000000;
  }

tick.current_time_us = GetCurrentTimeUs();

在策略端收到行情时
uint64_t current_us = GetCurrentTimeUs();
uint64_t delay_us = current_us - tick.current_time_us;

tick延迟大应该是由于ZeroMQ延迟大。
解决办法：开发基于共享内存的行情分发模块，可以让通信时延降低至1us以内。
