### ISSUE TITLE
Any plan on measuring tick to trade latency?

### ISSUE THREAD

**Issue by liutongwei** [DuckDuckDuck0/ft#20]
是否有开发计划测算 tick to trade 的延迟？

比如使用`chrono`提供的 API `std::chrono::steady_clock::now().time_since_epoch()` 计算 real time latency；或者 tsc frequency 校准不同 CPU core 后计算 CPU time latency？

**Comment by DuckDuckDuck0** [comment]
这个时间测算还是很有必要的，后面想对性能做优化的话必须要有时间相关的指标。如果能用rdtscp+绑定cpu的方法我觉得是比较合理的，而chrono本身有一微秒的开销，会导致比较大误差。不知道你那边是否能对这个功能提供支持呢😜

**Comment by liutongwei** [comment]
之前为了简单我都直接用`chrono`来测算 wall clock time。

有个问题不同的gateway支持绑定cpu吗？比如ctp底层应该是它本身来维护线程异步，如果[ctp不支持绑核](https://www.zhihu.com/question/28898780/answer/260286107)的话，`OnRtnDepthMarketData`和`SendOrder`之间因为上下文切换导致时延会较高。

只考虑`OrderManagementSystem `和`Strategy`绑核的话，之前有看过饶大佬的[tscns](https://github.com/MengRao/tscns)实现方法，具体到程序里还得改，我再熟悉熟悉:sweat_smile:

**Comment by DuckDuckDuck0** [comment]
api里面有自己的线程确实是个问题，绑核的话需要用taskset来操作，不够灵活。倒是可以先研究下别的方法😄

**Comment by songzhao831** [comment]
其实主要是策略里的算法多线程需要绑核， 但这里框架怎么做还是需要多考虑一下。
常见的方式是： tick来后会收集tick数据， 每到一个新的tick,就要把之前的收集的数据用放到多线程（可能要多核并行，如何绑cpu）里运算， 出结果后再去下单。
