### ISSUE TITLE
python的策略demo是否还能使用

### ISSUE THREAD

**Issue by shiniantianlang** [DuckDuckDuck0/ft#21]
@DuckDuckDuck0 您好，python的demo使用redis进行通信，添加zmq通信后，使用zmq发生tick和订单回报，python是否还能使用，是不是需要手动切换回redis通信？

**Comment by DuckDuckDuck0** [comment]
现在用不了，目前协议是通过cereal进行序列化，和之前的直接传输原始二进制数据不一样，需要给python也加上cereal序列化的功能才能够使用

**Comment by shiniantianlang** [comment]
知道了，辛苦！
