### ISSUE TITLE
之前专注于开发交易平台模块，现在开始对各个量化交易组件的研究及开发（即策略侧组件的开发）

### ISSUE THREAD

**Issue by DuckDuckDuck0** [DuckDuckDuck0/ft#9]

**Comment by DuckDuckDuck0** [comment]
交易平台的开发基本趋于稳定，经过大量的模拟环境压力测试，除了无法计算ETF可供申赎的仓位，其余功能均能正常运作

**Comment by DuckDuckDuck0** [comment]
trading engine中的strategy目录现只作为一个策略与平台交互的demo，远远没有达到可以上生产环境的level，后续所有的算法交易组件均会在algo_framework中实现

**Comment by bulalala** [comment]
能请教下centos的编译环境吗，linux不熟

**Comment by DuckDuckDuck0** [comment]
> 能请教下centos的编译环境吗，linux不熟

不好意思啊上周比较忙没看GitHub，centos下的话，gcc、g++的版本7以上、cmake 3.0以上即可编译，要运行的话再装个redis-server就行了。上面几个工具应该都可以通过yum来安装

**Comment by DuckDuckDuck0** [comment]
> 能请教下centos的编译环境吗，linux不熟

如果有哪里不明白的话可以加我qq：502019611，或是邮件kevin.lau.gd@gmail.com联系我，我可以帮你搭下环境
